In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import sys

In [ ]:
print(f"Pandas version:{pd.__version__}")
print(f"Numpy version:{np.__version__}")

Pandas version:2.2.2
Numpy version:2.0.2

In [ ]:
#Series
arr1=np.array([10,20,30,40])
print(arr1)

series1=pd.Series([10,20,30,40], name="Ages")
print(series1)

[10 20 30 40]
0    10
1    20
2    30
3    40
Name: Ages, dtype: int64

In [ ]:
#DataFrames
manual_df=pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 45, 31, 19],
    "Income":[50000, 85000, 62000, 22000]
})
print("\nManually created DataFrame:\n", manual_df)
print("\nDataFrame shape(rows, columns):", manual_df.shape)

Manually created DataFrame:
       Name  Age  Income
0    Alice   25   50000
1      Bob   45   85000
2  Charlie   31   62000
3    David   19   22000

DataFrame shape(rows, columns): (4, 3)

In [ ]:
import io
csv_data="""customerid,age,gender,income,purchased
101,25,F,50000.0,no
102,47,M,85000.0,yes
103,,F,62000.0,yes
104,31,M,,no
105,19,F,22000.0,no
106,52,,98000.0, yes
"""
print(csv_data)

customerid,age,gender,income,purchased
101,25,F,50000.0,no
102,47,M,85000.0,yes
103,,F,62000.0,yes
104,31,M,,no
105,19,F,22000.0,no
106,52,,98000.0, yes

In [ ]:
df=pd.read_csv(io.StringIO(csv_data))
print(df)
print(df.shape)

   customerid   age gender   income purchased
0         101  25.0      F  50000.0        no
1         102  47.0      M  85000.0       yes
2         103   NaN      F  62000.0       yes
3         104  31.0      M      NaN        no
4         105  19.0      F  22000.0        no
5         106  52.0    NaN  98000.0       yes
(6, 5)

In [ ]:
print("Shape (rows,cols):",df.shape)
print("Columns:\n",         df.columns.tolist())
print("Indices:\n",          df.index.tolist())
print("\nData Types:\n",df.dtypes)

Shape (rows,cols): (6, 5)
Columns:
 ['customerid', 'age', 'gender', 'income', 'purchased']
Indices:
 [0, 1, 2, 3, 4, 5]

Data Types:
 customerid      int64
age           float64
gender         object
income        float64
purchased      object
dtype: object

In [ ]:
df["gender"].astype("str")
df.dtypes

customerid      int64
age           float64
gender         object
income        float64
purchased      object
dtype: object

In [ ]:

df[["customerid","age"]]

   customerid   age
0         101  25.0
1         102  47.0
2         103   NaN
3         104  31.0
4         105  19.0
5         106  52.0

In [ ]:
slice_df=df.iloc[1:4,1:4]     #last value not count
slice_df

    age gender   income
1  47.0      M  85000.0
2   NaN      F  62000.0
3  31.0      M      NaN

In [ ]:
row_record=df.loc[1:4,"age":"purchased"]    #last value count
row_record

    age gender   income purchased
1  47.0      M  85000.0       yes
2   NaN      F  62000.0       yes
3  31.0      M      NaN        no
4  19.0      F  22000.0        no

In [ ]:
row_record=df.loc[1:4,["age","purchased"]]
row_record

    age purchased
1  47.0       yes
2   NaN       yes
3  31.0        no
4  19.0        no

In [ ]:
df['income']>60000.0

0    False
1     True
2     True
3    False
4    False
5     True
Name: income, dtype: bool

In [ ]:
df[df["income"]>60000.0]

   customerid   age gender   income purchased
1         102  47.0      M  85000.0       yes
2         103   NaN      F  62000.0       yes
5         106  52.0    NaN  98000.0       yes

In [ ]:
df[df["age"]>25]

   customerid   age gender   income purchased
1         102  47.0      M  85000.0       yes
3         104  31.0      M      NaN        no
5         106  52.0    NaN  98000.0       yes

In [ ]:
df["age"]>25

0    False
1     True
2    False
3     True
4    False
5     True
Name: age, dtype: bool

In [ ]:
df.dtypes

customerid      int64
age           float64
gender         object
income        float64
purchased      object
dtype: object

In [ ]:
df['income']

0    50000.0
1    85000.0
2    62000.0
3        NaN
4    22000.0
5    98000.0
Name: income, dtype: float64

In [ ]:
df[(df["income"]>40000) & (df["gender"]=="F")]

   customerid   age gender   income purchased
0         101  25.0      F  50000.0        no
2         103   NaN      F  62000.0       yes

In [ ]:
df[(df['age']>25) | (df["gender"]=="F")]

   customerid   age gender   income purchased
0         101  25.0      F  50000.0        no
1         102  47.0      M  85000.0       yes
2         103   NaN      F  62000.0       yes
3         104  31.0      M      NaN        no
4         105  19.0      F  22000.0        no
5         106  52.0    NaN  98000.0       yes

In [ ]:
#Day11

df.isnull().sum()

customerid    0
age           1
gender        1
income        1
purchased     0
dtype: int64

In [ ]:
mean=df["age"].mean()
print(mean)

34.8

In [ ]:
mean=df["age"].mean()
df["age"]=df["age"].fillna(mean)
print(mean)
print(df.isnull().sum())

34.8
customerid    0
age           0
gender        1
income        1
purchased     0
dtype: int64

In [ ]:
mean=df["income"].mean()
df["income"]=df["income"].fillna(mean)
print(mean)
print(df.isnull().sum())

63400.0
customerid    0
age           0
gender        1
income        0
purchased     0
dtype: int64

In [ ]:
df=df.dropna()
df.isnull().sum()

customerid    0
age           0
gender        0
income        0
purchased     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  5 non-null      int64
 1   age         5 non-null      float64
 2   gender      5 non-null      object
 3   income      5 non-null      float64
 4   purchased   5 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 240.0+ bytes

In [ ]:
df

   customerid   age gender   income purchased
0         101  25.0      F  50000.0        no
1         102  47.0      M  85000.0       yes
2         103  34.8      F  62000.0       yes
3         104  31.0      M  63400.0        no
4         105  19.0      F  22000.0        no

In [ ]:
df.groupby("gender")[["income","age"]].mean()

              income        age
gender
F       44666.666667  26.266667
M       74200.000000  39.000000